export const userInfo = {
    name: "黄仁卓",
    sex: "男",
    grade: "高三",
    studentID: 'U201812216',
    class: "软工1801",
    school: "华中科技大学",
    email: "13989776543@163.com",
    avatarUrl:'https://tse4-mm.cn.bing.net/th/id/OIP-C.HzFBPAh3rV010ZB5QkvHAQHaFj?w=200&h=150&c=7&o=5&dpr=1.5&pid=1.7'
}
export const statisticsBySubject=[
    {
        name:"语文",
        value:9,

    },
    {
        name:"数学",
        value:17,

    }, {
        name:"物理",
        value:6,

    }, {
        name:"英语",
        value:9,

    }, {
        name:"化学",
        value:12,

    }, {
        name:"政治",
        value:3,

    }, {
        name:"地理",
        value:5,

    },
]





export const SimulatedData =
    [{
        courseId: 12343,
        courseName: '逻辑与幽默',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东九",
    },
        {
            courseId: 12343,
            courseName: '营养与健康',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        }, {
        courseId: 12343,
        courseName: '食品安全与卫生',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    }, {
        courseId: 12343,
        courseName: '深度中国',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    },
        {
            courseId: 12343,
            courseName: '民国历史人物',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseId: 12343,
            courseName: '晚清历史人物研究',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseId: 12343,
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '黄仁卓',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseId: 12343,
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        }, {
        courseName: '111111',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    }, {
        courseName: '逻辑与幽默',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        }]


