export const userInfo = {
    name: "黄仁卓",
    sex: "男",
    grade: "高三",
    studentID: 'U201812216',
    class: "软工1801",
    school: "华中科技大学",
    email: "13989776543@163.com",
    avatarUrl: 'https://th.bing.com/th/id/R0ebc3a3de377bed841b8d61ceec52cf2?rik=y15BDTvL75YX1A&riu=http%3a%2f%2fupload.taihai' +
        'net.com%2f2017%2f0506%2f1494040346648.png&ehk=p%2f%2b6y4kRZEqWs5Xz6FJiYuDcxrMn0KqQpwSsPo%2fvjRA%3d&risl=&pid=ImgRaw'
}
export const statisticsBySubject = [
    {
        name: "语文",
        value: 9,
    },
    {
        name: "数学",
        value: 17,
    }, {
        name: "物理",
        value: 6,
    }, {
        name: "英语",
        value: 9,
    }, {
        name: "化学",
        value: 12,
    }, {
        name: "政治",
        value: 3,
    }, {
        name: "地理",
        value: 5,
    },
]


export const statisticsByDate = {
    dates: ['6月12号', '6月13号', '6月14号', '6月15号', '6月16号', '6月17号', '6月18号'],
    textNums: [23, 14, 16, 38, 26, 22, 25]
}


export const SimulatedData =
    [{
        courseId: 12343,
        courseName: '逻辑与幽默',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东九",
    },
        {
            courseId: 12343,
            courseName: '营养与健康',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        }, {
        courseId: 12343,
        courseName: '食品安全与卫生',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    }, {
        courseId: 12343,
        courseName: '深度中国',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    },
        {
            courseId: 12343,
            courseName: '民国历史人物',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseId: 12343,
            courseName: '晚清历史人物研究',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseId: 12343,
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '黄仁卓',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseId: 12343,
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        }, {
        courseName: '111111',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    }, {
        courseName: '逻辑与幽默',
        courseType: '沟通与管理',
        courseHours: 32,
        courseCredit: 2,
        capacity: 180,
        courseCollege: '新闻学院',
        teacherName: "黄仁卓",
        teacherTitle: "副教授",
        courseWeek: "4-11",
        courseTime: "周三9-12",
        courseLocation: "东久",
    },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        },
        {
            courseName: '逻辑与幽默',
            courseType: '沟通与管理',
            courseHours: 32,
            courseCredit: 2,
            capacity: 180,
            courseCollege: '新闻学院',
            teacherName: "黄仁卓",
            teacherTitle: "副教授",
            courseWeek: "4-11",
            courseTime: "周三9-12",
            courseLocation: "东久",
        }]


